name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main

      - name: Build
        uses: TartanLlama/actions-eleventy@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}