name: Eleventy Build
on: [push]

env:
  TEST: ${{ secrets.TEST }}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
            
      - run: npm ci

      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: eventyryoga.dk
